[package]
name = "ibc-ckb_contracts-mock_contracts-can_update_without_ownership_lock"
version = "0.1.0-alpha.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2021"
license = "MIT"
description = "This contract is a mock contract, and it is used for testing."
homepage = "https://github.com/synapseweb3/ibc-ckb-contracts"
repository = "https://github.com/synapseweb3/ibc-ckb-contracts"

[dependencies]
ckb-std = "0.13.0"

[features]
default = []
debugging = []
